info:
  contact: {}
paths:
  /register:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"","data":""}'
          schema:
            type: string
      summary: account register
      tags:
      - Register
swagger: "2.0"
